### ISSUE TITLE
Test on more Plone versions on Travis

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/pas.plugins.headers#4]
Currently we test Plone 5.1.0. Updating to 5.1.6 somehow pulled in the `Zope` package instead of `Zope2`, and during test this [gives an error](https://travis-ci.com/collective/pas.plugins.headers/builds/134433438):

```
Traceback (most recent call last):
  File "/home/travis/build/collective/pas.plugins.headers/src/pas/plugins/headers/tests/test_exportimport.py", line 3, in <module>
    from pas.plugins.headers.testing import PAS_PLUGINS_HEADERS_INTEGRATION_TESTING  # noqa
  File "/home/travis/build/collective/pas.plugins.headers/src/pas/plugins/headers/testing.py", line 2, in <module>
    from plone.app.testing import applyProfile
  File "/home/travis/build/collective/pas.plugins.headers/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/__init__.py", line 4, in <module>
    from plone.app.testing.helpers import applyProfile
  File "/home/travis/build/collective/pas.plugins.headers/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/helpers.py", line 5, in <module>
    from plone.app.testing import layers
  File "/home/travis/build/collective/pas.plugins.headers/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/layers.py", line 19, in <module>
    from plone.testing import zope
ImportError: cannot import name zope
```

**Comment by mauritsvanrees** [comment]
Fixed with PR #5.
